# TODO: CHECK WHY INITBOT IS PLOTED TWICE !!! ?
# TODO: Make docker display chatbot module output (+ logs)
version: '2'
services:
  web:
    build: ..
    ports:
      - "8000:8000"
    volumes:
      - /finder/py_proj/chatbot/DeepQA/chatbot_website/logs:/root/DeepQA/chatbot_website/logs
      - /finder/py_proj/chatbot/DeepQA/save:/root/DeepQA/save
      - /finder/py_proj/chatbot/DeepQA/data:/root/DeepQA/data
    depends_on:
      - redis
  redis:
    image: redis
